### ISSUE TITLE
Sprint 0: Técnica de Estimación a utilizar

### ISSUE THREAD

**Issue by jorgecons** [PupiUTN/proyecto-final#130]
https://docs.google.com/document/d/11kxTc04yCnO8GYm__DGwznPApTIje8ZICoKpDI8lIlA

**Comment by jorgecons** [comment]
@zeditio @fbackhaus @efradiaz @LorenzattiGabriel  que alguien revise el docuemento, estan ambas partes.
https://drive.google.com/open?id=0Byr9ri8uSADhVjF6VlR1U3hOZmM

**Comment by jorgecons** [comment]
@zeditio @fbackhaus @efradiaz @LorenzattiGabriel que alguien revise el docuemento, estan ambas partes.
https://drive.google.com/open?id=0Byr9ri8uSADhVjF6VlR1U3hOZmM

**Comment by zeditio** [comment]
hay partes de humo y poco concreto.
Me gustaron las metricas y la parte de agil.

No daria mucha vuelta con la documentación, esta aprobada a mi entender.
