### ISSUE TITLE
Yo como Equipo quiero documentar el Sprint 1 [1]

### ISSUE THREAD

**Issue by zeditio** [PupiUTN/proyecto-final#165]
https://drive.google.com/open?id=1aunKOKX-uMQrNc8O1wNA5oRydSCb9cc5h_2I1hW7CIk
Ahi está, revisen gente

**Comment by jorgecons** [comment]
https://drive.google.com/open?id=1aunKOKX-uMQrNc8O1wNA5oRydSCb9cc5h_2I1hW7CIk
Ahi está, revisen gente
